// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDfrwoCEO6gQXCzL2IkcA4GqYUwBc-rtVk',
    appId: '1:758516699446:web:ed77bd384b0e31a1382397',
    messagingSenderId: '758516699446',
    projectId: 'flutter-salon-web',
    authDomain: 'flutter-salon-web.firebaseapp.com',
    storageBucket: 'flutter-salon-web.appspot.com',
    measurementId: 'G-9Z859196VF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFiHDmcU27NeDa0Ig7jZLd1FmXQoPZ_ws',
    appId: '1:758516699446:android:040a1250968d47fc382397',
    messagingSenderId: '758516699446',
    projectId: 'flutter-salon-web',
    storageBucket: 'flutter-salon-web.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2xphhshBUIJI4ZAkWgBpx8Pi9fVC5uQQ',
    appId: '1:758516699446:ios:c7a83b637e9fa18c382397',
    messagingSenderId: '758516699446',
    projectId: 'flutter-salon-web',
    storageBucket: 'flutter-salon-web.appspot.com',
    iosClientId: '758516699446-hiog1opdg648e328soccoob618pdfbv1.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterSalon',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB2xphhshBUIJI4ZAkWgBpx8Pi9fVC5uQQ',
    appId: '1:758516699446:ios:c7a83b637e9fa18c382397',
    messagingSenderId: '758516699446',
    projectId: 'flutter-salon-web',
    storageBucket: 'flutter-salon-web.appspot.com',
    iosClientId: '758516699446-hiog1opdg648e328soccoob618pdfbv1.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterSalon',
  );
}
